name: Auto AI Review Updater

on:
  schedule:
    - cron: "0 */6 * * *"   # Every 6 hours
  workflow_dispatch:        # Allow manual trigger from Actions tab

jobs:
  update-reviews:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies (clean)
        run: |
          pip install --upgrade pip
          pip uninstall -y openai || true
          pip install "openai==1.13.3" --no-cache-dir
          pip install tweepy requests beautifulsoup4

      - name: Debug Check installed OpenAI version
        run: |
          python -c "import openai; print('✅ OpenAI version:', openai.__version__)"

      - name: Run auto_update.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: python auto_update.py

      - name: Commit and push updates
        run: |
          git config --global user.name "AICashKickBot"
          git config --global user.email "bot@aicashkick.com"
          git add index.html archive.html || true
          git commit -m "🤖 Auto-updated AI reviews" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
