name: Auto AI Review Updater

on:
  schedule:
    - cron: "0 12 * * *"  # Daily at noon UTC
  workflow_dispatch:

jobs:
  update-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai requests beautifulsoup4
          python -c "import openai; print('OpenAI version:', openai.__version__)"

      - name: Run auto_update.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          if [ -z "$OPENAI_API_KEY" ]; then echo "Error: OPENAI_API_KEY not set!"; exit 1; fi
          python auto_update.py

      - name: Commit and push updates
        uses: EndBug/add-and-commit@v9
        with:
          add: '*.html'
          message: '🤖 Auto-updated AI reviews - ${{ github.run_number }}'
          push: true
