name: Auto AI Review Updater

on:
  schedule:
    - cron: "0 12 * * *" # runs every day at noon UTC
  workflow_dispatch:

jobs:
  update-reviews:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --force-reinstall "openai==1.13.3" tweepy requests beautifulsoup4


      - name: Run auto-update script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: python auto_update.py

      - name: Commit and push changes
        run: |
          git config user.name "AI Cash Kick Bot"
          git config user.email "bot@aicashkick.com"
          git add index.html
          git commit -m "Auto-update reviews $(date)" || echo "No changes"
          git push
