      - name: Commit and Push Changes
        run: |
          git config --global user.email "bot@aicashkick.com"
          git config --global user.name "AI Cash Kick Bot"
          git add index.html
          git commit -m "Auto-updated AI reviews $(date)" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
