name: Auto AI Review Updater

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  update-reviews:
    runs-on: ubuntu-22.04   # ← switch runner
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"   # ← older compatible interpreter


      - name: Clean and Install Dependencies
        run: |
          pip uninstall -y openai httpx || true
          rm -rf ~/.cache/pip
          python -m pip install --upgrade pip
          python -m pip install --no-cache-dir --force-reinstall "openai==1.3.9"
          python -m pip install tweepy requests beautifulsoup4
          python -c "import openai; print('✅ OpenAI version:', openai.__version__)"




      - name: Run auto_update.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: python auto_update.py

      - name: Commit and push updates
        run: |
          git config --global user.name "AICashKickBot"
          git config --global user.email "bot@aicashkick.com"
          git add index.html archive.html || true
          git commit -m "🤖 Auto-updated AI reviews" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
