name: Auto AI Review Updater

on:
  schedule:
    - cron: "0 12 * * *"  # Runs every day at noon UTC
  workflow_dispatch:

jobs:
  update-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: pip install openai tweepy requests

      - name: Run Auto Update Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: python auto_update.py

      - name: Commit and Push Changes
        run: |
          git config --global user.email "bot@aicashkick.com"
          git config --global user.name "AI Cash Kick Bot"
          git add index.html
          git commit -m "Auto-updated AI reviews $(date)"
          git push
